### ISSUE TITLE
Invert only specific slider(s)

### ISSUE THREAD

**Issue by satsukiyatoshi** [omriharel/deej#101]
Hello.
1-Thanks a lot for this projet and sharing it for free
2-Thanks again
3-i've build my first one today but a inverted 3 of my 7 sliders, i've seen in the yaml that it's possible to invert all sliders, is there any way to invert only some specific slider?

Thanks ^^

**Comment by omriharel** [comment]
Hello @satsukiyatoshi, thanks for writing and for the kind words.

Inverting a single/specific sliders isn't possible by means of changing the configuration, but you can change the Arduino sketch to flip the values of specific sliders by substracting `1023 - value` for the specific value(s) that need to be flipped. The best way to deal with this is of course to flip the GND and VCC pins on the miswired potentiometers and to make sure they're identical on all pots - rather than making a code change.

Good luck!
