### ISSUE TITLE
Pop_OS! missing dependency libappindicator3-dev

### ISSUE THREAD

**Issue by TetsujinXLIV** [omriharel/deej#110]
I didn't see anybody else with this issue. But I am trying to compile from source and I need the dependency:
libappindicator3-dev but it seems this was removed in favor of libayatana-appindicator3-1

Is there something that can be changed to tell it to use the new libayatana instead?

**Comment by JonathanPartain** [comment]
What I did is that I modified the version of getlantern/systray to the latest version v1.2.2 in the `go.mod` file, and then I could build

**Comment by TetsujinXLIV** [comment]
Thanks this fixed it!

**Comment by Lefuneste83** [comment]
Indeed, in order to compile for Linux in recent versions (currently under Linux Mint 21.3) you have to :

**sudo apt install libgtk-3-dev libayatana-appindicator3-dev libwebkit2gtk-4.0-dev**

Then edit go.mod and change :
**github.com/getlantern/systray v0.0.0-20200324212034-d3ab4fd25d99**
to
**github.com/getlantern/systray v1.2.2**

**Comment by stefan-matic** [comment]
@Lefuneste83 solution worked for me. Should we create a PR for this?
