### ISSUE TITLE
Volume Increasing in Step of Three (3)

### ISSUE THREAD

**Issue by RedRambo** [omriharel/deej#13]
When monitoring application volumes with Volume Mixer while changing with Deej, each application is increasing in volume in steps of three (3). Is there anyway to change to increase in single (1) steps?

**Comment by omriharel** [comment]
Hi @RedRambo, thanks for writing!

Volume adjustment is done at 3% increments as part of deej's built-in noise reduction, because no potentiometer comes completely noise-free. As of release v0.9.10, this has been made a config file option named `noise_reduction`. Setting it to `low` would allow you to change to 2% increments (assuming that your potentiometers produce minimal noise).

If you _absolutely_ require 1% increments (and are confident that your hardware is completely noise-free), you may manually change the noise reduction threshold specified in [`util/util.go`](https://github.com/omriharel/deej/blob/85ff793256927eadaa5583aabd7cb10e93f3fe2f/util/util.go#L103) to 0.005. This will require that you build deej from source.
