### ISSUE TITLE
Rotary Encoder

### ISSUE THREAD

**Issue by NolanWalkerIII** [omriharel/deej#15]
Hi There! Saw another project that would be cool to merge with this one. What about, like on some of the designs, having the master control as a dial that's also a rotary encoder? That way a press of the encoder could mute all, skip songs, etc? Just a thought thanks!

**Comment by omriharel** [comment]
Hi @NolanWalkerIII, thanks for writing.

deej is a very community-driven project - many people have created their own versions of deej's hardware, with some of them also modifying deej's firmware to work with alternate means of control such as rotary encoders.

You can see (and recreate most of) these builds in our [community showcase](https://showcase.deej.rocks). The mentioned modifications to deej's code (where applicable) are linked under the relevant build, usually under the author's fork of deej. While these aren't guaranteed to be officially supported, their authors also usually hang out in our [Discord server](https://discord.gg/nf88NJu) and can answer any questions you might have about their specific hardware setups.

I don't currently have plans to add official support for rotary encoders because:

- They're more complicated than potentiometers, which makes them less beginner-friendly
- Dealing with them in firmware can be daunting and hard to troubleshoot due to the wide range of different hardware components (and software libraries) available

Please feel free to drop by our Discord and reach out if you have more questions about this. Thanks!

**Comment by NolanWalkerIII** [comment]
Thank you! Excellent work :)
