### ISSUE TITLE
after Windows 10 upgrade and restart Deej doesn't launch. 

### ISSUE THREAD

**Issue by elliswalker** [omriharel/deej#31]
I've restarted my rig a handful of times, tried a few things like reinstalling drivers, etc. but everytime I click to launch Deej it never appears to run. system tray has nothing. task manager shows nothing. wondering how to fix. (I'm a novice at best, please be kind)

**Comment by omriharel** [comment]
Hi @elliswalker, thanks for writing.

Please provide the following contextual info to help me look into this for you.

- Has deej worked for you in the past? Did it only stop working after a system update?
- If it did, has anything about your hardware setup changed since the last time it worked? (Particularly with respect to USB or audio devices)
- Which OS version are you on? (You can type `winver` in the run menu to get the exact build info)
- Which deej version are you using?
- Is your config file still valid? (also, has the COM port for your deej hardware changed?)
- Do you see any errors at the bottom of your deej log file (this is found next to the deej executable, under `logs/deej-latest-run.log`)?
- Are there any systems notifications from deej that you might've missed?

**Comment by elliswalker** [comment]
Hi @omriharel 
After joining the Deej discord I got help tracking down what the issue was. 
the same day I updated my system I must've saved the yaml with a tab on the first commented out line, which seems to have caused the error. 
This is user error, and we can close since I've had the issue fixed. 

Thank you
