### ISSUE TITLE
Add current EXE to list 

### ISSUE THREAD

**Issue by maelremrem** [omriharel/deej#36]
It would be great if with a keyboard shortcut (or a right clic on the deej tray icon) we can add the current (or list the current apps) to a pot in the config.yaml
With the deej.unmapped you can use all the apps not bound and with the deej.current the full screen one. But I don't want any of that.
with the deej.shortcut (for exemple) and a key bind (found in the config.yaml) I can quickly add another exe to the list

**Comment by omriharel** [comment]
Hi there @maelremrem, thanks for writing.

I'm not sure that I understand how you are expecting this to work (like, how that functionality is meant to detect which app you're meaning to add and to which slider). Can you please clarify with a more specific example what you meant?

As a heads up, this is likely not something I'm willing to add because it doesn't seem useful for many users.

**Comment by maelremrem** [comment]
Thanks for your fast reply !
I will try to explain as best as I can
If I'm on a game that I didn't bind to a slider, and the deej.shortcut is on a Slider with a shortcut (like Shift + Ctrl + F12) the app automagically add the EXE that is focused on to the list of bind of that slider
I hope I was clear haha

**Comment by omriharel** [comment]
@maelremrem Yes, it's clear now - thanks!

There is a bit of a technical challenge with editing a YAML-formatted config file programatically, because it's difficult to preserve cosmetic details like comments etc. I do have plans to deal with this, but for a different feature I'm planning.

In the meantime, I do think that the `deej.unmapped` and `deej.current` options both provide a reasonable alternative. It's not 100% what you're requesting, but targeting a slider for app bindings vs. just using that slider to control unbound apps are very similar to one another.
