### ISSUE TITLE
[Feature]Deej remember setting after reboot

### ISSUE THREAD

**Issue by oddife** [omriharel/deej#39]
Is it possible to make deej remember the settings after a reboot?,  eg if I have the microphone muted or volume set to a specific level it should automatically remember that setting during the next startup.

**Comment by omriharel** [comment]
Hi there @oddife, thanks for writing.

If you're using potentiometers, which is what deej supports, the behavior you're describing is just a consequence of leaving them at their absolute positions. At startup, deej just sets all volume to whatever potentiometer readings it gets from serial - if it didn't do that, it wouldn't be doing its primary function which is to translate analog readings to app volumes.

If you're using rotary encoders (which deej _doesn't_ officially support), these aren't absolute as they can rotate infinitely to either direction. In this case it's up to you to take care of storing their current values to persist between reboots of the _Arduino hardware_. I've seen some people use an EEPROM for this, but I haven't done this myself and I'm not sure what the actual lifespan of a solution like this is (since you'd be writing to this EEPROM quite a lot).

At any case, this is consciously out-of-scope for the project because encoders aren't officially supported.

**Comment by oddife** [comment]
thank you for the replay, yes I'm using encoders as I needed to mute the inputs with that switch, EEPROM would be a bad idea so I was thinking could the software make a file that would write the values once they are changed and reload it every time the software starts.

**Comment by omriharel** [comment]
As I mentioned, this is out-of-scope for deej because it doesn't include support for encoders. You can still implement it for yourself in a fork, but this isn't going to be a core feature.
