### ISSUE TITLE
Invalid configiruation

### ISSUE THREAD

**Issue by blackfield3k** [omriharel/deej#42]
Hi there,

i have the issue that if a add multiple programs to one fader like stated in the manual i get an invalid configruation file error.

If i list the programs with commas, it seems to work but not stable

EDIT: ok i used tab to arange it nicely. Seems like deej doesn`t like this. it works with spaces.

But it takes a long time till changing of volume works

**Comment by omriharel** [comment]
Hi there @blackfield3k, thanks for writing.

The FAQ document (link in the main readme) has some commonly-asked questions about configuration editing, and how to make sure that your config file is valid before starting deej. I'm guessing that your config mixed tabs and spaces, which unfortunately doesn't quality as valid YAML. You should be able to use either tabs or spaces, but not both.

Regarding stablity issues, these usually have to do with unstable wiring on the problematic potentiometer (or another hardware fault with the pot in question).

Can you expand on the delay before changing volumes? It should be instant - if it isn't, there might be something else interfering with deej. This could be another audio-related software, an audio driver or a faulty sound card.

Please join our Discord server for more help with troubleshooting any issues you might have - it's usually better for this kind of thing. Thank you!

**Comment by blackfield3k** [comment]
Configuration is now working fine, even with multiple apps. As you said: dont mix spaces and tabs. 

I cant confirm that deej gets the values for sure but if i close deej and open a terminal values seem to change immediately. They are a bit noisy (mostly around the last digit), gonna fix that. 

I think the problem is/was deej getting confused with many open instances like chrome does for every tab. As i reduced the amount of apps, the problem was gone. 
But i am gonna get sure that nothing interferes with deej. Are there common suspects?

thanks for your help and this awesome piece of software

**Comment by omriharel** [comment]
@blackfield3k - A tiny bit of noise is to be expected with potentiometers, and deej does have inherent noise reduction built into it. You can fine-tune it to make it a bit more or less sensitive depending on your hardware (the `noise_reduction` config setting allows that).

I don't think I heard any previous reports for many running apps making deej run slower, but here are a few things you can try:

1. Check if the issue is isolated to a specific target, whether the `master` channel of a specific audio device (i.e., if you have Speakers connected to your main sound card and USB headphones that are their own audio device, check with either of them set as the default audio output) or a particular app
2. Check if you can replicate the slowness you're experiencing with deej not running - if it takes a while for Windows Mixer or the Windows volume UI to respond to your dragging, that's a pretty good indication something is wrong at the driver/audio card level. I wouldn't know how to fix that, though

Thank you for the kind words!

**Comment by blackfield3k** [comment]
@omriharel - Thanks for your suggestions. A 470uF cap between GND and 5V did the trick. Pots are now stable.

On first: it disappeared after i wrote my config.yaml completely new. What ever this was, it is gone.

What i suspect that cura interfered with the serial data stream, as it trys to connect to everything that is a virtual com port (i dont care if you are a 3D printer or not - i will connect) 

But great work and keep it up!

Maybe in the future it would be nice not only to read from the controller but also write to it
