### ISSUE TITLE
Deej.exe does not work with windows 11?

### ISSUE THREAD

**Issue by nabeelmoeen** [omriharel/deej#46]
looks like Windows have finally changed how the volume control works and removed the legacy mixer.
https://www.windowscentral.com/hidden-changes-you-may-have-missed-windows-11

I tried the deej.exe on my windows 11 setup, i can see the serial output changing on moving the sliders (on the arduino serial monitor), but the windows volume isn't moving.

**Comment by NegussugeN** [comment]
That's definitely odd.  Mine is working just fine with Windows 11 without any changes.  Silly question, but are you sure you have the correct serial port defined in the deej config file?

**Comment by stephensilber** [comment]
I just ran as administrator and mine properly launched and is working as well. I previously ran without administrator permissions and it was not opening in my taskbar.

**Comment by nabeelmoeen** [comment]
thanks for the inputs, will retest today and update.

**Comment by nabeelmoeen** [comment]
Thank you @stephensilber and @NegussugeN.

I will chalk this off to user error. 
running as administrator worked for me, also, 2 of my potentiometers seemed to be faulty.

**Comment by omriharel** [comment]
Hi there @nabeelmoeen and @stephensilber - apologies for not responding earlier, it's been quite a busy time for me!

I hope you're enjoying deej. I have a few quick questions about the solution you found, that might help shine a light on this for other users who see this thread in the future.

1. Did you previously use deej with Windows 10, or did you try it on Windows 11 for the first time?
2. If you've used deej previously on Windows 10: where (in what directory) did you place its executable on your PC? Did you need to run as administrator back then?
3. Where is the deej executable currently placed on your Windows 11 PC?

The reason I'm asking this is because I suspect that nothing changed between Windows 10 and 11 in terms of the permissions that deej inherently requires, and by default deej doesn't (and shouldn't!) need any special permissions to run. But there is one soft limitation on both Windows 10 and (I suspect) Windows 11: deej has to be inside a directory that doesn't require admin privileges to access, otherwise it can't open its logfile for writing.

For many users, placing the directory with deej's executable on their desktop or in another directory that they have full access to (such as in `C:\deej`) worked fine, whereas using a system location like `Program Files` or their user directory would fail and require them to (unnecessarily) use the "run as administrator" option.

If that's the case on your end, I'd love to hear if moving deej (and its config file) removes the restriction of needing admin privileges to run. Thanks for taking the time!

**Comment by JeanCharpentier** [comment]
Hello !
I know this topic is old, but I had a similar problem. After upgrading to Windows 11, Deej was not able to manage audio.
**What worked for me** was to disconnect and reconnect the Arduino, and "sync" it with the Arduino App. Once done, I started Deej and voila !
Hope this will help.
