### ISSUE TITLE
Faders not working

### ISSUE THREAD

**Issue by ghost** [omriharel/deej#49]
Tried default config as well as alternative assignments, but neither work for any control. Debug shows faders are detected fine, but they won't control any volumes.

**Comment by omriharel** [comment]
Hi there @SightsSet, thanks for writing.

I will need more information to help with this, such as seeing the serial monitor output from your Arduino. Due to the interactive nature of issues like this, I highly recommend using a platform such as our Discord server to help with troubleshooting. Please feel free to reach out there as well if you prefer. Thanks!

**Comment by ghost** [comment]
Here's the output of my serial monitor.
![serial_output](https://user-images.githubusercontent.com/59065106/145746030-45f1bc33-4e61-42c7-be88-f247aa28bc77.JPG)

**Comment by ghost** [comment]
Gnd wire was on raw by accident. Everything works now.
