### ISSUE TITLE
My device generates bluescreens

### ISSUE THREAD

**Issue by hEVIq** [omriharel/deej#71]
Hello, 

have any1 the same problem? My device generates bluescreens, idk how to stop it. I recognize that because after disconnect device bluescreens stops. I love that device, pls help me.
Windows 11 64-bit.
Bluescreen code: CH341S64.SYS

**Comment by mrouillard** [comment]
I had exactly the same, mind you it was on Windows 10.
I found the solution on the Deej Discord server. Sorry I cannot find the exact post, but the idea was that everytime Windows update would "update" the driver to a faulty one. So I uninstalled it, installed one that works (from https://learn.sparkfun.com/tutorials/how-to-install-ch340-drivers/all#windows-710) and made sure it is not updated in the next windows update (in Windows 10, I think it was via the device manager, look for the USB serial 340 device, and disable updates). Not sure how to do it under Windows 11. But I can tell you that I have had no bluescreen anymore since then.

**Comment by omriharel** [comment]
Hi there @hEVIq, thanks for writing! I apologize for the delay in responding.

The deej PC software is very unlikely to make your system BSOD by itself, but Arduino boards (and more notoriously cheap variants like the CH34X) can cause system crashes in some cases, usually due to a fault in their driver code. There are a lot of different driver versions for these boards all around the Internet, and it's important to try to get them from trustworthy and well-known sources. Sparkfun is one such source, as pointed out by @mrouillard in his comment.

I'll close this issue and make a note to document driver-related details more clearly in the project README or FAQ. Thank you!
