### ISSUE TITLE
MPV not detected

### ISSUE THREAD

**Issue by riegojerey** [omriharel/deej#76]
I'm using the debug mode and whenever I try to open MPV, the debug mode can't seem to find it.

**Comment by ajs124** [comment]
This might be because it doesn't set `application.process.binary`. I might have a patch for this in the next few days.

**Comment by omriharel** [comment]
Hi there @riegojerey, thanks for writing! I apologize for the delay in responding.

I realize there is a PR by @ajs124 that probably fixes this issue for you, but I was wondering if you'd also be able to provide logs or a short recording to help me document this for my internal backlog. I would like this give this more attention in a future release.

Please feel free to respond with more details if you're able to get them, otherwise I'll treat this as something that has a workaround available (in the form of @ajs124's fork) and close. Thank you!
