### ISSUE TITLE
Cannot control "Line in at rear panel (Blue) (Realtek High Definition Audio)"

### ISSUE THREAD

**Issue by jl-p** [omriharel/deej#97]
i tried 

"Line in at rear panel (Blue) (Realtek High Definition Audio)"
Line in at rear panel (Blue) (Realtek High Definition Audio)
"Line in at rear panel (Blue)"
Line in at rear panel (Blue)

but cant control the line input volume. 

Any idea how to do this

**Comment by omriharel** [comment]
Hi @jl-p, thanks for writing. 

I am guessing that this has to do with not matching the regular expression used to detect you targeting a device, because of there being two sets of parentheses. Please try renaming your device to something without parentheses, and then you should be able to use `whatever name you choose (Realtek High Definition Audio)` to target it.

Let me know if that works. Thanks!

**Comment by jl-p** [comment]
I reinstalled my pc between then and now. and now with new drivers the name of the line in is "Line In (2- High Definition Audio Device)"

and now it worked immidiatly.
so thx
